[package]
name = "kbparse"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#scroll = { version = "*" }

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
strip = true
