[package]
name = "kbparse"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kbparse-lib = { path = "../kbparse-lib" }
# kbparse-lib ="*"
clap = { version = "*", features = ["derive"] }
