name: kbparse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: precious
            name: precious-Darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: precious
            name: precious-Darwin-aarch64.tar.gz
            skip_tests: true
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
      - name: Install rustfmt and clippy
        run: |
          rustup component add rustfmt clippy

      # Format
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      
      # Test
      - uses: actions-rs/cargo@v1
        with:
          command: test



          # clippy:
          #   name: Clippy
          #   runs-on: ubuntu-latest
          #   steps:
          #     - name: Checkout sources
          #       uses: actions/checkout@v2
        

        

        