name: kbparse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-Darwin-x86_64.tar.gz
            command: both

    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      
      # Build
      - uses: actions-rs/cargo@v1
        with:
          command: build

      # Format
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      
      # Test
      - uses: actions-rs/cargo@v1
        with:
          command: test
