name: kbparse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-fmt-clippy-test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: macOS-14-aarch64
            os: macos-14`
            target: aarch64-apple-darwin
            bin: kbparse
            name: kbparse-macos13-aarch64.tar.gz

          - os_name: macOS-13-aarch64
            os: macos-13
            target: aarch64-apple-darwin
            bin: kbparse
            name: kbparse-macos13-aarch64.tar.gz

          - os_name: macOS-13-x86_64
            os: macos-13
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos13-x86_64.tar.gz

          - os_name: macOS-12-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos12-x86_64.tar.gz

          - os_name: macOS-12-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: kbparse
            name: kbparse-macos12-aarch64.tar.gz

          - os_name: macOS-11-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos11-x86_64.tar.gz

        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
          
      - name: Install rustfmt and clippy
        run: |
          rustup component add rustfmt clippy

      # Format
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      
      # Test
      - uses: actions-rs/cargo@v1
        with:
          command: test