name: Publish Crate to Crates.io

on:
  release:
    types:
      - created

env:
    CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and publish crate
        run: |
          # Set the necessary environment variables
          export CRATES_IO_TOKEN=${{ secrets.CRATES_IO_TOKEN }}
        
          # Login
          cargo login $CRATES_IO_TOKEN

          # Dry run
          cargo publish -p kbparse-lib --dry-run
          
          # Build and publish the crate
          cargo publish -p kbparse-lib --locked
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
