name: Release

permissions:
  contents: write


  
on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always


jobs:
  Build-Package:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: macOS-13-aarch64
            os: macos-13
            target: aarch64-apple-darwin
            bin: kbparse
            name: kbparse-macos13-aarch64.tar.gz

          - os_name: macOS-13-x86_64
            os: macos-13
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos13-x86_64.tar.gz

          - os_name: macOS-12-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos12-x86_64.tar.gz

          - os_name: macOS-12-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: kbparse
            name: kbparse-macos12-aarch64.tar.gz

          - os_name: macOS-11-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: kbparse
            name: kbparse-macos11-x86_64.tar.gz
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Build Binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"  

      - name: Package Binary
        run: |
          tar cvzf ${{ matrix.platform.name }} target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          ls -l

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: ./${{ matrix.platform.name }}
      

  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - bin1: kbparse-macos13-aarch64.tar.gz
          - bin2: kbparse-macos13-x86_64.tar.gz
          - bin3: kbparse-macos12-x86_64.tar.gz
          - bin4: kbparse-macos12-aarch64.tar.gz
          - bin5: kbparse-macos11-x86_64.tar.gz


    name: Upload binaries to release
    needs: Build-Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
    
      - name: Display structure of downloaded files
        run: ls -R
        
      # - uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ${{ matrix.platform.name }}
      #     asset_name: ${{ matrix.platform.name }}
      #     tag: ${{ github.ref }}

